# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('press_release', models.TextField(db_index=True, verbose_name='Press Release')),
                ('photo', models.ImageField(upload_to='', verbose_name='Foto')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('site', models.CharField(max_length=200, verbose_name='Site')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.CharField(max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(max_length=120, null=True, verbose_name='Instagram')),
                ('twitter', models.CharField(max_length=120, null=True, verbose_name='Twitter')),
                ('snapchat', models.CharField(max_length=120, null=True, verbose_name='Snapchat')),
                ('slug', models.SlugField(blank=True, max_length=170)),
            ],
            options={
                'verbose_name': 'Artista',
                'db_table': 'artist',
                'verbose_name_plural': 'Artistas',
            },
        ),
    ]
