# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('artists', '0002_auto_20170112_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Gênero Musical'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(upload_to='artists/', verbose_name='Foto'),
        ),
    ]
