# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0002_auto_20170112_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(upload_to='artists/', verbose_name='Foto'),
        ),
    ]
