# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 20:02
from __future__ import unicode_literals

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20170120_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(upload_to=artists.models.photo_path_and_name, verbose_name='Foto'),
        ),
    ]
